import { convertFieldToArray, convertInputToArray, Field, Input } from "./input.ts";
import { IR } from "./ir.ts";

type Opcode = BlockOpcode | HiddenOpcode | MenuOpcode | string

const enum BlockOpcode {
    Motion_MoveSteps              = "motion_movesteps",
    Motion_TurnRight              = "motion_turnright",
    Motion_TurnLeft               = "motion_turnleft",
    Motion_Goto                   = "motion_goto",
    Motion_GotoXY                 = "motion_gotoxy",
    Motion_GlideTo                = "motion_glideto",
    Motion_GlideToXY              = "motion_glidesecstoxy",
    Motion_PointInDirection       = "motion_pointindirection",
    Motion_PointTowards           = "motion_pointtowards",
    Motion_ChangeX                = "motion_changexby",
    Motion_SetX                   = "motion_setx",
    Motion_SetY                   = "motion_sety",
    Motion_ChangeY                = "motion_changeyby",
    Motion_BounceIfOnEdge         = "motion_ifonedgebounce",
    Motion_SetRotationStyle       = "motion_setrotationstyle",
    Motion_PositionX              = "motion_xposition",
    Motion_PositionY              = "motion_yposition",
    Motion_Direction              = "motion_direction",
    Looks_SayFor                  = "looks_sayforsecs",
    Looks_Say                     = "looks_say",
    Looks_ThinkFor                = "looks_thinkforsecs",
    Looks_Think                   = "looks_think",
    Looks_SwitchCostumeTo         = "looks_switchcostumeto",
    Looks_NextCostume             = "looks_nextcostume",
    Looks_SwitchBackdropTo        = "looks_switchbackdropto",
    Looks_SwitchBackdropToAndWait = "looks_switchbackdroptoandwait",
    Looks_NextBackdrop            = "looks_nextbackdrop",
    Looks_ChangeSize              = "looks_changesizeby",
    Looks_SetSize                 = "looks_setsizeto",
    Looks_ChangeEffect            = "looks_changeeffectby",
    Looks_SetEffect               = "looks_seteffectto",
    Looks_ClearEffects            = "looks_cleargraphiceffects",
    Looks_Show                    = "looks_show",
    Looks_Hide                    = "looks_hide",
    Looks_GotoFrontBack           = "looks_gotofrontback",
    Looks_GoForwardBackward       = "looks_goforwardbackwardlayers",
    Looks_CostumeNumberName       = "looks_costumenumbername",
    Looks_BackdropNumberName      = "looks_backdropnumbername",
    Looks_Size                    = "looks_size",
    Sound_PlayUntil               = "sound_playutildone",
    Sound_Play                    = "sound_play",
    Sound_StopAll                 = "sound_stopallsounds",
    Sound_ChangeEffect            = "sound_changeeffectby",
    Sound_SetEffect               = "sound_seteffectto",
    Sound_ClearEffects            = "sound_cleareffects",
    Sound_ChangeVolume            = "sound_changevolumeby",
    Sound_SetVolume               = "sound_setvolumeto",
    Sound_Volume                  = "sound_volume",
    Event_WhenFlagClicked         = "event_whenflagclicked",
    Event_WhenKeyPressed          = "event_whenkeypressed",
    Event_WhenSelfClicked         = "event_whenthisspriteclicked",
    Event_WhenStageClicked        = "event_whenstageclicked",
    Event_WhenBackDropSwitchTo    = "event_whenbackdropswitchesto",
    Event_WhenGreaterThan         = "event_whengreaterthan",
    Event_WhenBroadcastReceived   = "event_whenbroadcastreceived",
    Event_Broadcast               = "event_broadcast",
    Event_BroadcastAndWait        = "event_broadcastandwait",
    Control_Wait                  = "control_wait",
    Control_Repeat                = "control_repeat",
    Control_Forever               = "control_forever",
    Control_If                    = "control_if",
    Control_IfElse                = "control_if_else",
    Control_WaitUntil             = "control_wait_until",
    Control_RepeatUntil           = "control_repeat_until",
    Control_Stop                  = "control_stop",
    Control_WhenStartAsClone      = "control_start_as_clone",
    Control_CreateClone           = "control_create_clone_of",
    Control_DeleteClone           = "control_delete_this_clone",
    Sensing_TouchingObject        = "sensing_touchingobject",
    Sensing_TouchingColor         = "sensing_touchingcolor",
    Sensing_ColorTouchingColor    = "sensing_coloristouchingcolor",
    Sensing_DistanceTo            = "sensing_distanceto",
    Sensing_AskAndWait            = "sensing_askandwait",
    Sensing_Answer                = "sensing_answer",
    Sensing_IsKeyPressed          = "sensing_keypressed",
    Sensing_IsMouseDown           = "sensing_mousedown",
    Sensing_MouseX                = "sensing_mousex",
    Sensing_MouseY                = "sensing_mousey",
    Sensing_SetDragMode           = "sensing_setdragmode",
    Sensing_Loudnees              = "sensing_loudness",
    Sensing_Timer                 = "sensing_timer",
    Sensing_ResetTimer            = "sensing_resettimer",
    Sensing_Of                    = "sensing_of",
    Sensing_Current               = "sensing_current",
    Sensing_DaySince2000          = "sensing_dayssince2000",
    Sensing_Username              = "sensing_username",
    Operator_Add                  = "operator_add",
    Operator_Sub                  = "operator_subtract",
    Operator_Mul                  = "operator_multiply",
    Operator_Div                  = "operator_divide",
    Operator_RandomBetween        = "operator_random",
    Operator_Gt                   = "operator_gt",
    Operator_Lt                   = "operator_lt",
    Operator_Eq                   = "operator_equals",
    Operator_And                  = "operator_and",
    Operator_Or                   = "operator_or",
    Operator_Not                  = "operator_not",
    Operator_Join                 = "operator_join",
    Operator_LetterOf             = "operator_letter_of",
    Operator_LengthOf             = "operator_length",
    Operator_Contains             = "operator_contains",
    Operator_Mod                  = "operator_mod",
    Operator_Round                = "operator_round",
    Operator_Mathop               = "operator_mathop",
    Data_Variable                 = "data_variable",
    Data_SetVariable              = "data_setvariableto",
    Data_ChangeVariable           = "data_chnagevariableby",
    Data_ShowVariable             = "data_showvariable",
    Data_HideVariable             = "data_hidevariable",
    Data_List                     = "data_listcontents",
    Data_AppendList               = "data_addtolist",
    Data_DeleteList               = "data_deleteoflist",
    Data_ClearList                = "data_deletealloflist",
    Data_InsertList               = "data_insertatlist",
    Data_ReplaceList              = "data_replaceitemoflist",
    Data_ItemOfList               = "data_itemoflist",
    Data_FindList                 = "data_itemnumoflist",
    Data_LengthOfList             = "data_lengthoflist",
    Data_ListContains             = "data_listcontainsitem",
    Data_ShowList                 = "data_showlist",
    Data_HideList                 = "data_hidelist",
    Procedures_Definition         = "procedures_definition",
    Procedures_Call               = "procedures_call",
    Procedures_Prototype          = "procedures_prototype",
    ProcArg_StringNumber          = "argument_reporter_string_number",
    ProcArg_Boolean               = "argument_reporter_boolean",
    Pen_Clear                     = "pen_clear",
    Pen_Stamp                     = "pen_stamp",
    Pen_Down                      = "pen_penDown",
    Pen_Up                        = "pen_penUp",
    Pen_SetColor                  = "pen_setPenColorToColor",
    Pen_ChangeColorParam          = "pen_changePenColorParamBy",
    Pen_SetColorParam             = "pen_setPenColorParamTo",
    Pen_ChangePenSize             = "pen_changePenSizeBy",
    Pen_SetPenSize                = "pen_setPenSizeTo",
}

const enum MenuOpcode {
    Motion_Goto            = "motion_goto_menu",
    Motion_GolideTo        = "motion_glideto_menu",
    Motion_GoPointTowards  = "motion_pointtowards",
    Looks_Costume          = "looks_costume",
    Looks_Backdrops        = "looks_backdrops",
    Sound_Sounds           = "sound_sounds_menu",
    Event_Broadcast        = "event_broadcast_menu",
    Event_TouchingObject   = "event_touchingobjectmenu",
    Control_CreateCloneOf  = "control_create_clone_of_menu",
    Sensing_TouchingObject = "sensing_touchingobjectmenu",
    Sensing_DistanceTo     = "sensing_distancetomenu",
    Sensing_Keys           = "sensing_keyoptions",
    Sensing_OfObject       = "sensing_of_object_menu",
}

const enum HiddenOpcode {
    Undefined                = "undefined",
    Looks_SetStrech          = "looks_setstrechto",
    Looks_ChangeStrech       = "looks_changestrechby",
    Event_WhenTouchingObject = "event_whentouchingobject",
    Control_ForEach          = "control_for_each",
    Control_While            = "control_while",
    Control_Counter          = "control_get_counter",
    Control_IncreaseCounter  = "control_incr_counter",
    Control_ResetCounter     = "control_clear_counter",
    Control_AllAtOnce        = "control_all_at_once",
    Sensing_IsLoudAvailable  = "sensing_loud",
    Sensing_UserId           = "sensing_userid",
    Procedures_Declaration   = "procedures_declaration",
    Pen_SetPenHueToNumber    = "pen_setPenHueToNumber",
    Pen_ChangePenHue         = "pen_changePenHueBy",
    Pen_SetPenShadeToNumber  = "pen_setPenShadeToNumber",
    Pen_ChangePenShade       = "pen_changePenShadeBy",
}

interface Block {
    id: string
    source: IR | null
    opcode: Opcode
    fields: Record<string, Field>
    inputs: Record<string, Input>
    next: string | null,
    parent: string | null,
    isShadow: boolean,
    isTopLevel: boolean,
    states: Record<string, unknown>
}

const blockToJson = (block: Block): object => {
    // deno-lint-ignore no-explicit-any
    const json: any = {
        ...block.states,
        opcode: block.opcode,
        next: block.next,
        parent: block.parent,
        inputs: Object.fromEntries(
            Object.entries(block.inputs)
                  .map(([k, v]) => [k, convertInputToArray(v)])
        ),
        fields: Object.fromEntries(
            Object.entries(block.fields)
                  .map(([k, v]) => [k, convertFieldToArray(v)])
        ),
        shadow: block.isShadow,
        topLevel: block.isTopLevel,
    }
    if (json.topLevel) {
        if (!json.x) json.x = 0
        if (!json.y) json.y = 0
    }
    return json
}

export {
    type Block,
    type Field,
    type Input,
    type Opcode,
    BlockOpcode,
    HiddenOpcode,
    MenuOpcode,
    blockToJson,
}